language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:
  - echo "Begin gradle tasks"

script:
  - ./gradlew test

after_script:
  - echo "Build done"
